version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
  db:
    image: postgres:latest
    environment:
        POSTGRES_PASSWORD: admin
        POSTGRES_DATABASE: facilita_db